# Setup
title:        Aftermath
tagline:      A post-apocalyptic augmented reality game
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Team 17
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
